undirected_graph_example: undirected_graph_example.c ../data_structures/graphs/undirected_graph/undirected_graph.c ../data_structures/stacks/array_stack/array_stack.c ../data_structures/queues/array_queue/array_queue.c
	gcc -o undirected_graph_example undirected_graph_example.c ../data_structures/graphs/undirected_graph/undirected_graph.c ../data_structures/stacks/array_stack/array_stack.c ../data_structures/queues/array_queue/array_queue.c -I.


